name: blog_club_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  android: true
  ios: true

  # color: "#BBC6D7"
  background_image: assets/images/splashbg.png
  image: assets/images/logo.png
  # color_dark:
  # background_image_dark:
  # image_dark:
  # fullscreen:
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Roman.otf
        - asset: assets/fonts/Avenir-Medium.ttf
        - asset: assets/fonts/Avenir-Book.otf
        - asset: assets/fonts/Avenir-Heavy.ttf

    - family: Muli-ExtraBold
      fonts:
        - asset: assets/fonts/Muli-ExtraBold.ttf
